<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>edu.hm.hafner</groupId>
    <artifactId>codingstyle-pom</artifactId>
    <version>7.0.0</version>
  </parent>

  <artifactId>karalight-assignment</artifactId>
  <version>2026-SNAPSHOT</version>

  <packaging>jar</packaging>

  <name>KaraLight assignments</name>
  <description>Provides a framework to compile and test KaraLight programs.
    It also integrates Maven and several static analysis tools.</description>

  <url>https://cs.hm.edu/~hafner</url>

  <licenses>
    <license>
      <name>MIT license</name>
      <comments>All source code is copyrighted by Ullrich Hafner and licensed under the MIT license.</comments>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>uhafner</id>
      <name>Ullrich Hafner</name>
      <email>ullrich.hafner@hm.edu</email>
      <organization>Munich University of Applied Sciences</organization>
      <organizationUrl>https://www.hm.edu/en/index.en.html</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/uhafner/karalight-assignment.git</connection>
    <developerConnection>scm:git:git@github.com:uhafner/karalight-assignment.git</developerConnection>
    <url>https://github.com/uhafner/karalight-assignment</url>
  </scm>

  <properties>
    <java.version>25</java.version>
    <source.encoding>UTF-8</source.encoding>
    <project.build.sourceEncoding>${source.encoding}</project.build.sourceEncoding>

    <module.name>${project.groupId}.karalight.assignment</module.name>
    <revapi.skip>true</revapi.skip>

    <karalight.version>26.0.0</karalight.version>

    <!-- Maven Plug-ins Configuration -->
    <asciidoctor.maven.plugin.version>3.2.0</asciidoctor.maven.plugin.version>
    <asciidoctorj.version>3.0.1</asciidoctorj.version>
    <asciidoctorj.diagram.version>3.2.1</asciidoctorj.diagram.version>
    <asciidoctorj.pdf.version>2.3.27</asciidoctorj.pdf.version>
    <jruby.version>9.2.7.0</jruby.version>
    <buildhelper.maven.plugin>3.3.0</buildhelper.maven.plugin>

    <!-- Maven Surefire ArgLine -->
    <argLine>-Djava.util.logging.config.file=logging.properties</argLine>

  </properties>

  <dependencies>
    <dependency>
      <groupId>de.i8k</groupId>
      <artifactId>karalight</artifactId>
      <version>${karalight.version}</version>
    </dependency>

  </dependencies>

  <build>

    <plugins>
      <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>${asciidoctor.maven.plugin.version}</version>
        <configuration>
          <requires>
            <require>asciidoctor-diagram</require>
          </requires>
          <logHandler>
            <failIf>
              <severity>ERROR</severity>
            </failIf>
          </logHandler>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>${asciidoctorj.version}</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-diagram</artifactId>
            <version>${asciidoctorj.diagram.version}</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>${asciidoctorj.pdf.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>generate-html-doc</id>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <backend>html5</backend>
              <attributes>
                <imagesdir>./</imagesdir>
                <icons>font</icons>
                <sectanchors>true</sectanchors>
                <idprefix />
                <idseparator>-</idseparator>
              </attributes>
            </configuration>
          </execution>
          <execution>
            <id>generate-pdf-doc</id>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <backend>pdf</backend>
              <attributes>
                <imagesdir>./</imagesdir>
                <icons>font</icons>
                <sectanchors>true</sectanchors>
                <idprefix />
                <idseparator>-</idseparator>
              </attributes>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <executions>
          <execution>
            <id>run-pmd-java</id>
            <goals>
              <goal>pmd</goal>
              <goal>check</goal>
              <goal>cpd</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <targetDirectory>${project.build.directory}/pmd-java</targetDirectory>
              <rulesets>
                <ruleset>etc/pmd-java-configuration.xml</ruleset>
              </rulesets>
              <includeTests>false</includeTests>
              <minimumTokens>50</minimumTokens>
              <printFailingErrors>true</printFailingErrors>
              <skip>${pmd.skip}</skip>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>

  </build>

</project>
